/**
 * Created by fegemo on 2/25/15.
 */
// if the database is empty on server start, create some sample data.
Meteor.startup(function () {
  Regions.remove({});
  if (Regions.find().count() === 0) {
    let regions = [
      {
        name: 'Noroeste de Minas',
        picture: 'paracatu.jpg',
        pictureCaption: 'Paracatu',
        cities: [
          'Arinos',
          'Bonfinópolis de Minas',
          'Buritis',
          'Cabeceira Grande',
          'Dom Bosco',
          'Formoso',
          'Natalândia',
          'Unaí',
          'Uruana de Minas',
          'Brasilândia de Minas',
          'Guarda-Mor',
          'João Pinheiro',
          'Lagamar',
          'Lagoa Grande',
          'Paracatu',
          'Presidente Olegário',
          'São Gonçalo do Abaeté',
          'Varjão de Minas',
          'Vazante'
        ]
      },
      {
        name: 'Norte de Minas',
        picture: 'montes-claros.jpg',
        pictureCaption: 'Montes Claros',
        cities: [
          'Bonito de Minas',
          'Chapada Gaúcha',
          'Cônego Marinho',
          'Icaraí de Minas',
          'Itacarambi',
          'Januária',
          'Juvenília',
          'Manga',
          'Matias Cardoso',
          'Miravânia',
          'Montalvânia',
          'Pedras de Maria da Cruz',
          'Pintópolis',
          'São Francisco',
          'São João das Missões',
          'Urucuia',
          'Catuti',
          'Espinosa',
          'Gameleiras',
          'Jaíba',
          'Janaúba',
          'Mamonas',
          'Mato Verde',
          'Monte Azul',
          'Nova Porteirinha',
          'Pai Pedro',
          'Porteirinha',
          'Riacho dos Machados',
          'Serranópolis de Minas',
          'Águas Vermelhas',
          'Berizal',
          'Curral de Dentro',
          'Divisa Alegre',
          'Fruta de Leite',
          'Indaiabira',
          'Montezuma',
          'Ninheira',
          'Novorizonte',
          'Rio Pardo de Minas',
          'Rubelita',
          'Salinas',
          'Santa Cruz de Salinas',
          'Santo Antônio do Retiro',
          'São João do Paraíso',
          'Taiobeiras',
          'Vargem Grande do Rio Pardo',
          'Buritizeiro',
          'Ibiaí',
          'Jequitaí',
          'Lagoa dos Patos',
          'Lassance',
          'Pirapora',
          'Riachinho',
          'Santa Fé de Minas',
          'São Romão',
          'Várzea da Palma',
          'Brasília de Minas',
          'Campo Azul',
          'Capitão Enéias',
          'Claro dos Poções',
          'Coração de Jesus',
          'Francisco Sá',
          'Glaucilândia',
          'Ibiracatu',
          'Japonvar',
          'Juramento',
          'Lontra',
          'Luislândia',
          'Mirabela',
          'Montes Claros',
          'Patis',
          'Ponto Chique',
          'São João da Lagoa',
          'São João da Ponte',
          'São João do Pacuí',
          'Ubaí',
          'Varzelândia',
          'Verdelândia',
          'Botumirim',
          'Cristália',
          'Grão-Mogol',
          'Itacambira',
          'Josenópolis',
          'Padre Carvalho',
          'Bocaiúva',
          'Engenheiro Navarro',
          'Francisco Dumont',
          'Guaraciama',
          'Olhos-d\'Água'
        ]
      },
      {
        name:'Jequitinhonha',
        picture: 'diamantina.jpg',
        pictureCaption: 'Diamantina',
        cities: [
          'Couto de Magalhães de Minas',
          'Datas',
          'Diamantina',
          'Felício dos Santos',
          'Gouveia',
          'Presidente Kubitschek',
          'São Gonçalo do Rio Preto',
          'Senador Modestino Gonçalves',
          'Angelândia',
          'Aricanduva',
          'Berilo',
          'Capelinha',
          'Carbonita',
          'Chapada do Norte',
          'Francisco Badaró',
          'Itamarandiba',
          'Jenipapo de Minas',
          'José Gonçalves de Minas',
          'Leme do Prado',
          'Minas Novas',
          'Turmalina',
          'Veredinha',
          'Araçuaí',
          'Caraí',
          'Coronel Murta',
          'Itinga',
          'Novo Cruzeiro',
          'Padre Paraíso',
          'Ponto dos Volantes',
          'Virgem da Lapa',
          'Cachoeira de Pajeú',
          'Comercinho',
          'Itaobim',
          'Medina',
          'Pedra Azul',
          'Almenara',
          'Bandeira',
          'Divisópolis',
          'Felisburgo',
          'Jacinto',
          'Jequitinhonha',
          'Joaíma',
          'Jordânia',
          'Mata Verde',
          'Monte Formoso',
          'Palmópolis',
          'Rio do Prado',
          'Rubim',
          'Salto da Divisa',
          'Santa Maria do Salto',
          'Santo Antônio do Jacinto'
        ]
      },
      {
        name: 'Vale do Mucuri',
        picture: 'teofilo-otoni.jpg',
        pictureCaption: 'Teófilo Otoni',
        cities: [
          'Ataléia',
          'Catuji',
          'Franciscópolis',
          'Frei Gaspar',
          'Itaipé',
          'Ladainha',
          'Malacacheta',
          'Novo Oriente de Minas',
          'Ouro Verde de Minas',
          'Pavão',
          'Poté',
          'Setubinha',
          'Teófilo Otôni',
          'Águas Formosas',
          'Bertópolis',
          'Carlos Chagas',
          'Crisólita',
          'Fronteira dos Vales',
          'Maxacalis',
          'Nanuque',
          'Santa Helena de Minas',
          'Serra dos Aimorés',
          'Umburatiba'
        ]
      },
      {
        name: 'Triângulo Mineiro/Alto Paranaíba',
        picture: 'uberlandia.jpg',
        pictureCaption: 'Uberlândia',
        cities: [
          'Cachoeira Dourada',
          'Capinópolis',
          'Gurinhatã',
          'Ipiaçu',
          'Ituiutaba',
          'Santa Vitória',
          'Araguari',
          'Araporã',
          'Canápolis',
          'Cascalho Rico',
          'Centralina',
          'Indianópolis',
          'Monte Alegre de Minas',
          'Prata',
          'Tupaciguara',
          'Uberlândia',
          'Abadia dos Dourados',
          'Coromandel',
          'Cruzeiro da Fortaleza',
          'Douradoquara',
          'Estrela do Sul',
          'Grupiara',
          'Iraí de Minas',
          'Monte Carmelo',
          'Patrocínio',
          'Romaria',
          'Serra do Salitre',
          'Arapuá',
          'Carmo do Paranaíba',
          'Guimarânia',
          'Lagoa Formosa',
          'Matutina',
          'Patos de Minas',
          'Rio Paranaíba',
          'Santa Rosa da Serra',
          'São Gotardo',
          'Tiros',
          'Campina Verde',
          'Carneirinho',
          'Comendador Gomes',
          'Fronteira',
          'Frutal',
          'Itapajipe',
          'Iturama',
          'Limeira do Oeste',
          'Pirajuba',
          'Planura',
          'São Francisco de Sales',
          'União de Minas',
          'Água Comprida',
          'Campo Florido',
          'Conceição das Alagoas',
          'Conquista',
          'Delta',
          'Uberaba',
          'Veríssimo',
          'Araxá',
          'Campos Altos',
          'Ibiá',
          'Nova Ponte',
          'Pedrinópolis',
          'Perdizes',
          'Pratinha',
          'Sacramento',
          'Santa Juliana',
          'Tapira'
        ]
      },
      {
        name: 'Central Mineira',
        picture: 'tres-marias.jpg',
        pictureCaption: 'Três Marias',
        cities: [
          'Abaeté',
          'Biquinhas',
          'Cedro do Abaeté',
          'Morada Nova de Minas',
          'Paineiras',
          'Pompéu',
          'Três Marias',
          'Augusto de Lima',
          'Buenópolis',
          'Corinto',
          'Curvelo',
          'Felixlândia',
          'Inimutaba',
          'Joaquim Felício',
          'Monjolos',
          'Morro da Garça',
          'Presidente Juscelino',
          'Santo Hipólito',
          'Araújos',
          'Bom Despacho',
          'Dores do Indaiá',
          'Estrela do Indaiá',
          'Japaraíba',
          'Lagoa da Prata',
          'Leandro Ferreira',
          'Luz',
          'Martinho Campos',
          'Moema',
          'Quartel Geral',
          'Serra da Saudade'
        ]
      },
      {
        name: 'Metropolitana de Belo Horizonte',
        picture: 'belo-horizonte.jpg',
        pictureCaption: 'Belo Horizonte'
      },
      {
        name: 'Vale do Rio Doce',
        picture: 'governador-valadares.jpg',
        pictureCaption: 'Governador Valadares'
      },
      {
        name: 'Oeste de Minas',
        picture: 'divinopolis.jpg',
        pictureCaption: 'Divinópolis'
      },
      {
        name: 'Sul/Sudoeste de Minas',
        picture: 'varginha.jpg',
        pictureCaption: 'Varginha'
      },
      {
        name: 'Campo das Vertentes',
        picture: 'sao-joao-del-rei.jpg',
        pictureCaption: 'São João del Rei'
      },
      {
        name: 'Zona da Mata',
        picture: 'vicosa.jpg',
        pictureCaption: 'Viçosa'
      }];

    _.each(regions, function(region) {
      var regionId = Regions.insert(_.omit(region, 'cities'));
      _.each(region.cities || [], function(city) {
        Cities.insert({ name: city, regionId: regionId });
      });
    });
  }
});
